name: End to End Tests

on:
  repository_dispatch:
    types:
      - 'vercel.deployment.ready'

run-name: Vercel Deployment Event - ${{ github.event.client_payload.project.name }} (${{ github.event.client_payload.state.type }})

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Vercel Dispatch Debug
        uses: vercel/repository-dispatch/actions/debug@v1

      - name: 'Notify Vercel'
        uses: 'vercel/repository-dispatch/actions/status@v1'
        with:
          name: 'Vercel - portfolio: tests'

      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm install -g yarn && yarn

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps --only-shell

      - name: Run Playwright Tests
        run: yarn playwright test
        env:
          BASE_URL: ${{ github.event.client_payload.url }}
          #VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
