name: End to End Tests

on:
  repository_dispatch:
    types:
      - 'vercel.deployment.ready'

run-name: E2E Tests on ${{ github.event.client_payload.project.name }} deployment (${{ github.event.client_payload.environment }})

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: 'Notify Vercel'
        uses: 'vercel/repository-dispatch/actions/status@v1'
        with:
          name: 'Vercel - portfolio: tests'

      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm install -g yarn && yarn

      - name: Install Playwright Browsers
        run: |
          yarn playwright install chromium --only-shell
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk-bridge2.0-0 libdrm2 libxcomposite1 libxdamage1 libxrandr2 libgbm1

      - name: Run Playwright Tests
        run: yarn playwright test
        env:
          BASE_URL: ${{ github.event.client_payload.url }}

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: tests/reports/
          retention-days: 30
